/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: limewrap.i */

#define SWIGMODULE limewrap
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <lime/LimeSuite.h>


#include <stdint.h>		// Use the C99 official header

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_limewrap_a37b50197546cf98(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_limewrap_a37b50197546cf98(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SUCCESS_get_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)(int)LMS_SUCCESS;
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetDeviceList_limewrap_a37b50197546cf98(_gostring_* _swig_go_0) {
  lms_info_str_t *arg1 = (lms_info_str_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_info_str_t **)&_swig_go_0; 
  
  result = (int)LMS_GetDeviceList((char (*)[256])arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_Open_limewrap_a37b50197546cf98(lms_device_t **_swig_go_0, _gostring_ _swig_go_1, void *_swig_go_2) {
  lms_device_t **arg1 = (lms_device_t **) 0 ;
  char *arg2 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t ***)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)LMS_Open(arg1,(char const (*))arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_LMS_Close_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  result = (int)LMS_Close(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_Disconnect_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  result = (int)LMS_Disconnect(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_LMS_IsOpen_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, intgo _swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  int arg2 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (bool)LMS_IsOpen(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_LMS_CH_TX_get_limewrap_a37b50197546cf98() {
  bool result;
  bool _swig_go_result;
  
  
  result = (bool)(bool)LMS_CH_TX;
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_LMS_CH_RX_get_limewrap_a37b50197546cf98() {
  bool result;
  bool _swig_go_result;
  
  
  result = (bool)(bool)LMS_CH_RX;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_range_t_min_set_limewrap_a37b50197546cf98(lms_range_t *_swig_go_0, double _swig_go_1) {
  lms_range_t *arg1 = (lms_range_t *) 0 ;
  float_type arg2 ;
  
  arg1 = *(lms_range_t **)&_swig_go_0; 
  arg2 = (float_type)_swig_go_1; 
  
  if (arg1) (arg1)->min = arg2;
  
}


double _wrap_lms_range_t_min_get_limewrap_a37b50197546cf98(lms_range_t *_swig_go_0) {
  lms_range_t *arg1 = (lms_range_t *) 0 ;
  float_type result;
  double _swig_go_result;
  
  arg1 = *(lms_range_t **)&_swig_go_0; 
  
  result = (float_type) ((arg1)->min);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_range_t_max_set_limewrap_a37b50197546cf98(lms_range_t *_swig_go_0, double _swig_go_1) {
  lms_range_t *arg1 = (lms_range_t *) 0 ;
  float_type arg2 ;
  
  arg1 = *(lms_range_t **)&_swig_go_0; 
  arg2 = (float_type)_swig_go_1; 
  
  if (arg1) (arg1)->max = arg2;
  
}


double _wrap_lms_range_t_max_get_limewrap_a37b50197546cf98(lms_range_t *_swig_go_0) {
  lms_range_t *arg1 = (lms_range_t *) 0 ;
  float_type result;
  double _swig_go_result;
  
  arg1 = *(lms_range_t **)&_swig_go_0; 
  
  result = (float_type) ((arg1)->max);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_range_t_step_set_limewrap_a37b50197546cf98(lms_range_t *_swig_go_0, double _swig_go_1) {
  lms_range_t *arg1 = (lms_range_t *) 0 ;
  float_type arg2 ;
  
  arg1 = *(lms_range_t **)&_swig_go_0; 
  arg2 = (float_type)_swig_go_1; 
  
  if (arg1) (arg1)->step = arg2;
  
}


double _wrap_lms_range_t_step_get_limewrap_a37b50197546cf98(lms_range_t *_swig_go_0) {
  lms_range_t *arg1 = (lms_range_t *) 0 ;
  float_type result;
  double _swig_go_result;
  
  arg1 = *(lms_range_t **)&_swig_go_0; 
  
  result = (float_type) ((arg1)->step);
  _swig_go_result = result; 
  return _swig_go_result;
}


lms_range_t *_wrap_new_lms_range_t_limewrap_a37b50197546cf98() {
  lms_range_t *result = 0 ;
  lms_range_t *_swig_go_result;
  
  
  result = (lms_range_t *)calloc(1, sizeof(lms_range_t));
  *(lms_range_t **)&_swig_go_result = (lms_range_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_lms_range_t_limewrap_a37b50197546cf98(lms_range_t *_swig_go_0) {
  lms_range_t *arg1 = (lms_range_t *) 0 ;
  
  arg1 = *(lms_range_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


intgo _wrap_LMS_TESTSIG_NONE_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_TESTSIG_NONE;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_TESTSIG_NCODIV8_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_TESTSIG_NCODIV8;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_TESTSIG_NCODIV4_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_TESTSIG_NCODIV4;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_TESTSIG_NCODIV8F_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_TESTSIG_NCODIV8F;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_TESTSIG_NCODIV4F_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_TESTSIG_NCODIV4F;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_TESTSIG_DC_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_TESTSIG_DC;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_Init_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  result = (int)LMS_Init(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetNumChannels_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  result = (int)LMS_GetNumChannels(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_EnableChannel_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, bool _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  bool arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  
  result = (int)LMS_EnableChannel(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetSampleRate_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, double _swig_go_1, long long _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  float_type arg2 ;
  size_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (float_type)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = (int)LMS_SetSampleRate(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetSampleRate_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double *_swig_go_3, double *_swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type *arg4 = (float_type *) 0 ;
  float_type *arg5 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(float_type **)&_swig_go_3; 
  arg5 = *(float_type **)&_swig_go_4; 
  
  result = (int)LMS_GetSampleRate(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetSampleRateRange_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, lms_range_t *_swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  lms_range_t *arg3 = (lms_range_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = *(lms_range_t **)&_swig_go_2; 
  
  result = (int)LMS_GetSampleRateRange(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetLOFrequency_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (float_type)_swig_go_3; 
  
  result = (int)LMS_SetLOFrequency(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetLOFrequency_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double *_swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type *arg4 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(float_type **)&_swig_go_3; 
  
  result = (int)LMS_GetLOFrequency(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetLOFrequencyRange_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, lms_range_t *_swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  lms_range_t *arg3 = (lms_range_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = *(lms_range_t **)&_swig_go_2; 
  
  result = (int)LMS_GetLOFrequencyRange(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_PATH_NONE_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_PATH_NONE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_LMS_PATH_LNAH_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_PATH_LNAH;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_LMS_PATH_LNAL_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_PATH_LNAL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_LMS_PATH_LNAW_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_PATH_LNAW;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_LMS_PATH_TX1_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_PATH_TX1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_LMS_PATH_TX2_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_PATH_TX2;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetAntennaList_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, _gostring_* _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  lms_name_t *arg4 = (lms_name_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(lms_name_t **)&_swig_go_3; 
  
  result = (int)LMS_GetAntennaList(arg1,arg2,arg3,(char (*)[16])arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetAntenna_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, long long _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  size_t arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (size_t)_swig_go_3; 
  
  result = (int)LMS_SetAntenna(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetAntenna_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = (int)LMS_GetAntenna(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetAntennaBW_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, long long _swig_go_3, lms_range_t *_swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  size_t arg4 ;
  lms_range_t *arg5 = (lms_range_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (size_t)_swig_go_3; 
  arg5 = *(lms_range_t **)&_swig_go_4; 
  
  result = (int)LMS_GetAntennaBW(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetNormalizedGain_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (float_type)_swig_go_3; 
  
  result = (int)LMS_SetNormalizedGain(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetGaindB_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, intgo _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  unsigned int arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  
  result = (int)LMS_SetGaindB(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetNormalizedGain_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double *_swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type *arg4 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(float_type **)&_swig_go_3; 
  
  result = (int)LMS_GetNormalizedGain(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetGaindB_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, intgo *_swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  unsigned int *arg4 = (unsigned int *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(unsigned int **)&_swig_go_3; 
  
  result = (int)LMS_GetGaindB(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetLPFBW_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (float_type)_swig_go_3; 
  
  result = (int)LMS_SetLPFBW(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetLPFBW_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double *_swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type *arg4 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(float_type **)&_swig_go_3; 
  
  result = (int)LMS_GetLPFBW(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetLPFBWRange_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, lms_range_t *_swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  lms_range_t *arg3 = (lms_range_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = *(lms_range_t **)&_swig_go_2; 
  
  result = (int)LMS_GetLPFBWRange(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetLPF_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, bool _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  bool arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  
  result = (int)LMS_SetLPF(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetGFIRLPF_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, bool _swig_go_3, double _swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  bool arg4 ;
  float_type arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  arg5 = (float_type)_swig_go_4; 
  
  result = (int)LMS_SetGFIRLPF(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_Calibrate_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double _swig_go_3, intgo _swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  double arg4 ;
  unsigned int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (double)_swig_go_3; 
  arg5 = (unsigned int)_swig_go_4; 
  
  result = (int)LMS_Calibrate(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_LoadConfig_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)LMS_LoadConfig(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_LMS_SaveConfig_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)LMS_SaveConfig(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_LMS_SetTestSignal_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, intgo _swig_go_3, short _swig_go_4, short _swig_go_5) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  lms_testsig_t arg4 ;
  int16_t arg5 ;
  int16_t arg6 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (lms_testsig_t)_swig_go_3; 
  arg5 = (int16_t)_swig_go_4; 
  arg6 = (int16_t)_swig_go_5; 
  
  result = (int)LMS_SetTestSignal(arg1,arg2,arg3,arg4,arg5,arg6);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetTestSignal_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, lms_testsig_t *_swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  lms_testsig_t *arg4 = (lms_testsig_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(lms_testsig_t **)&_swig_go_3; 
  
  result = (int)LMS_GetTestSignal(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GFIR1_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_GFIR1;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GFIR2_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_GFIR2;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GFIR3_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_GFIR3;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_NCO_VAL_COUNT_get_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)(int)LMS_NCO_VAL_COUNT;
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetSampleRateDir_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, double _swig_go_2, long long _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  float_type arg3 ;
  size_t arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (float_type)_swig_go_2; 
  arg4 = (size_t)_swig_go_3; 
  
  result = (int)LMS_SetSampleRateDir(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetNCOFrequency_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double *_swig_go_3, double _swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type *arg4 = (float_type *) 0 ;
  float_type arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(float_type **)&_swig_go_3; 
  arg5 = (float_type)_swig_go_4; 
  
  result = (int)LMS_SetNCOFrequency(arg1,arg2,arg3,(double const *)arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetNCOFrequency_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double *_swig_go_3, double *_swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type *arg4 = (float_type *) 0 ;
  float_type *arg5 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(float_type **)&_swig_go_3; 
  arg5 = *(float_type **)&_swig_go_4; 
  
  result = (int)LMS_GetNCOFrequency(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetNCOPhase_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double *_swig_go_3, double _swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type *arg4 = (float_type *) 0 ;
  float_type arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(float_type **)&_swig_go_3; 
  arg5 = (float_type)_swig_go_4; 
  
  result = (int)LMS_SetNCOPhase(arg1,arg2,arg3,(double const *)arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetNCOPhase_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, double *_swig_go_3, double *_swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  float_type *arg4 = (float_type *) 0 ;
  float_type *arg5 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(float_type **)&_swig_go_3; 
  arg5 = *(float_type **)&_swig_go_4; 
  
  result = (int)LMS_GetNCOPhase(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetNCOIndex_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, intgo _swig_go_3, bool _swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  int arg4 ;
  bool arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  
  result = (int)LMS_SetNCOIndex(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetNCOIndex_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = (int)LMS_GetNCOIndex(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_ReadParam_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, struct LMS7Parameter *_swig_go_1, short *_swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  struct LMS7Parameter arg2 ;
  uint16_t *arg3 = (uint16_t *) 0 ;
  struct LMS7Parameter *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  argp2 = (struct LMS7Parameter *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null struct LMS7Parameter");
  }
  arg2 = (struct LMS7Parameter)*argp2;
  
  arg3 = *(uint16_t **)&_swig_go_2; 
  
  result = (int)LMS_ReadParam(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_WriteParam_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, struct LMS7Parameter *_swig_go_1, short _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  struct LMS7Parameter arg2 ;
  uint16_t arg3 ;
  struct LMS7Parameter *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  argp2 = (struct LMS7Parameter *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null struct LMS7Parameter");
  }
  arg2 = (struct LMS7Parameter)*argp2;
  
  arg3 = (uint16_t)_swig_go_2; 
  
  result = (int)LMS_WriteParam(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetGFIRCoeff_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, intgo _swig_go_3, double *_swig_go_4, long long _swig_go_5) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  lms_gfir_t arg4 ;
  float_type *arg5 = (float_type *) 0 ;
  size_t arg6 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (lms_gfir_t)_swig_go_3; 
  arg5 = *(float_type **)&_swig_go_4; 
  arg6 = (size_t)_swig_go_5; 
  
  result = (int)LMS_SetGFIRCoeff(arg1,arg2,arg3,arg4,(double const *)arg5,arg6);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetGFIRCoeff_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, intgo _swig_go_3, double *_swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  lms_gfir_t arg4 ;
  float_type *arg5 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (lms_gfir_t)_swig_go_3; 
  arg5 = *(float_type **)&_swig_go_4; 
  
  result = (int)LMS_GetGFIRCoeff(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetGFIR_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1, long long _swig_go_2, intgo _swig_go_3, bool _swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  size_t arg3 ;
  lms_gfir_t arg4 ;
  bool arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = (lms_gfir_t)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  
  result = (int)LMS_SetGFIR(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_VCTCXOWrite_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, short _swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint16_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (uint16_t)_swig_go_1; 
  
  result = (int)LMS_VCTCXOWrite(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_VCTCXORead_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, short *_swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint16_t *arg2 = (uint16_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(uint16_t **)&_swig_go_1; 
  
  result = (int)LMS_VCTCXORead(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_Reset_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  result = (int)LMS_Reset(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_ReadLMSReg_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, intgo _swig_go_1, short *_swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint32_t arg2 ;
  uint16_t *arg3 = (uint16_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  arg3 = *(uint16_t **)&_swig_go_2; 
  
  result = (int)LMS_ReadLMSReg(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_WriteLMSReg_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, intgo _swig_go_1, short _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint32_t arg2 ;
  uint16_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  arg3 = (uint16_t)_swig_go_2; 
  
  result = (int)LMS_WriteLMSReg(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_ReadFPGAReg_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, intgo _swig_go_1, short *_swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint32_t arg2 ;
  uint16_t *arg3 = (uint16_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  arg3 = *(uint16_t **)&_swig_go_2; 
  
  result = (int)LMS_ReadFPGAReg(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_WriteFPGAReg_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, intgo _swig_go_1, short _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint32_t arg2 ;
  uint16_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  arg3 = (uint16_t)_swig_go_2; 
  
  result = (int)LMS_WriteFPGAReg(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_ReadCustomBoardParam_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, char _swig_go_1, double *_swig_go_2, _gostring_ _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint8_t arg2 ;
  float_type *arg3 = (float_type *) 0 ;
  char *arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  arg3 = *(float_type **)&_swig_go_2; 
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  result = (int)LMS_ReadCustomBoardParam(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_LMS_WriteCustomBoardParam_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, char _swig_go_1, double _swig_go_2, _gostring_ _swig_go_3) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint8_t arg2 ;
  float_type arg3 ;
  char *arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  arg3 = (float_type)_swig_go_2; 
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  result = (int)LMS_WriteCustomBoardParam(arg1,arg2,arg3,(char const (*))arg4);
  _swig_go_result = result; 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_LMS_GetClockFreq_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, long long _swig_go_1, double *_swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  size_t arg2 ;
  float_type *arg3 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = *(float_type **)&_swig_go_2; 
  
  result = (int)LMS_GetClockFreq(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SetClockFreq_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, long long _swig_go_1, double _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  size_t arg2 ;
  float_type arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (float_type)_swig_go_2; 
  
  result = (int)LMS_SetClockFreq(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_Synchronize_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  result = (int)LMS_Synchronize(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GPIORead_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, char *_swig_go_1, long long _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = (int)LMS_GPIORead(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GPIOWrite_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, char *_swig_go_1, long long _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = (int)LMS_GPIOWrite(arg1,(unsigned char const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GPIODirRead_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, char *_swig_go_1, long long _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = (int)LMS_GPIODirRead(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GPIODirWrite_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, char *_swig_go_1, long long _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(uint8_t **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = (int)LMS_GPIODirWrite(arg1,(unsigned char const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_EnableCalibCache_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, bool _swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  bool arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  result = (int)LMS_EnableCalibCache(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetChipTemperature_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, long long _swig_go_1, double *_swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  size_t arg2 ;
  float_type *arg3 = (float_type *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = *(float_type **)&_swig_go_2; 
  
  result = (int)LMS_GetChipTemperature(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_meta_t_timestamp_set_limewrap_a37b50197546cf98(lms_stream_meta_t *_swig_go_0, long long _swig_go_1) {
  lms_stream_meta_t *arg1 = (lms_stream_meta_t *) 0 ;
  uint64_t arg2 ;
  
  arg1 = *(lms_stream_meta_t **)&_swig_go_0; 
  arg2 = (uint64_t)_swig_go_1; 
  
  if (arg1) (arg1)->timestamp = arg2;
  
}


long long _wrap_lms_stream_meta_t_timestamp_get_limewrap_a37b50197546cf98(lms_stream_meta_t *_swig_go_0) {
  lms_stream_meta_t *arg1 = (lms_stream_meta_t *) 0 ;
  uint64_t result;
  long long _swig_go_result;
  
  arg1 = *(lms_stream_meta_t **)&_swig_go_0; 
  
  result = (uint64_t) ((arg1)->timestamp);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_meta_t_waitForTimestamp_set_limewrap_a37b50197546cf98(lms_stream_meta_t *_swig_go_0, bool _swig_go_1) {
  lms_stream_meta_t *arg1 = (lms_stream_meta_t *) 0 ;
  bool arg2 ;
  
  arg1 = *(lms_stream_meta_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  if (arg1) (arg1)->waitForTimestamp = arg2;
  
}


bool _wrap_lms_stream_meta_t_waitForTimestamp_get_limewrap_a37b50197546cf98(lms_stream_meta_t *_swig_go_0) {
  lms_stream_meta_t *arg1 = (lms_stream_meta_t *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(lms_stream_meta_t **)&_swig_go_0; 
  
  result = (bool) ((arg1)->waitForTimestamp);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_meta_t_flushPartialPacket_set_limewrap_a37b50197546cf98(lms_stream_meta_t *_swig_go_0, bool _swig_go_1) {
  lms_stream_meta_t *arg1 = (lms_stream_meta_t *) 0 ;
  bool arg2 ;
  
  arg1 = *(lms_stream_meta_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  if (arg1) (arg1)->flushPartialPacket = arg2;
  
}


bool _wrap_lms_stream_meta_t_flushPartialPacket_get_limewrap_a37b50197546cf98(lms_stream_meta_t *_swig_go_0) {
  lms_stream_meta_t *arg1 = (lms_stream_meta_t *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(lms_stream_meta_t **)&_swig_go_0; 
  
  result = (bool) ((arg1)->flushPartialPacket);
  _swig_go_result = result; 
  return _swig_go_result;
}


lms_stream_meta_t *_wrap_new_lms_stream_meta_t_limewrap_a37b50197546cf98() {
  lms_stream_meta_t *result = 0 ;
  lms_stream_meta_t *_swig_go_result;
  
  
  result = (lms_stream_meta_t *)calloc(1, sizeof(lms_stream_meta_t));
  *(lms_stream_meta_t **)&_swig_go_result = (lms_stream_meta_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_lms_stream_meta_t_limewrap_a37b50197546cf98(lms_stream_meta_t *_swig_go_0) {
  lms_stream_meta_t *arg1 = (lms_stream_meta_t *) 0 ;
  
  arg1 = *(lms_stream_meta_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_lms_stream_t_handle_set_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, long long _swig_go_1) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  size_t arg2 ;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  if (arg1) (arg1)->handle = arg2;
  
}


long long _wrap_lms_stream_t_handle_get_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  result =  ((arg1)->handle);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_t_isTx_set_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, bool _swig_go_1) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  bool arg2 ;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  if (arg1) (arg1)->isTx = arg2;
  
}


bool _wrap_lms_stream_t_isTx_get_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  result = (bool) ((arg1)->isTx);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_t_channel_set_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, intgo _swig_go_1) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->channel = arg2;
  
}


intgo _wrap_lms_stream_t_channel_get_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->channel);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_t_fifoSize_set_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, intgo _swig_go_1) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->fifoSize = arg2;
  
}


intgo _wrap_lms_stream_t_fifoSize_get_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->fifoSize);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_t_throughputVsLatency_set_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, float _swig_go_1) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  float arg2 ;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  if (arg1) (arg1)->throughputVsLatency = arg2;
  
}


float _wrap_lms_stream_t_throughputVsLatency_get_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  result = (float) ((arg1)->throughputVsLatency);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_FMT_F32_lms_stream_t_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_FMT_F32;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_FMT_I16_lms_stream_t_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_FMT_I16;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_FMT_I12_lms_stream_t_limewrap_a37b50197546cf98() {
  int result;
  intgo _swig_go_result;
  
  
  result = LMS_FMT_I12;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_t_dataFmt_set_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, intgo _swig_go_1) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  int arg2 ;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1 && sizeof(int) == sizeof((arg1)->dataFmt)) *(int*)(void*)&((arg1)->dataFmt) = arg2;
  
}


intgo _wrap_lms_stream_t_dataFmt_get_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  result = (int) ((arg1)->dataFmt);
  _swig_go_result = result; 
  return _swig_go_result;
}


lms_stream_t *_wrap_new_lms_stream_t_limewrap_a37b50197546cf98() {
  lms_stream_t *result = 0 ;
  lms_stream_t *_swig_go_result;
  
  
  result = (lms_stream_t *)calloc(1, sizeof(lms_stream_t));
  *(lms_stream_t **)&_swig_go_result = (lms_stream_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_lms_stream_t_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_lms_stream_status_t_active_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, bool _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  bool arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  if (arg1) (arg1)->active = arg2;
  
}


bool _wrap_lms_stream_status_t_active_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (bool) ((arg1)->active);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_status_t_fifoFilledCount_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, intgo _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->fifoFilledCount = arg2;
  
}


intgo _wrap_lms_stream_status_t_fifoFilledCount_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->fifoFilledCount);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_status_t_fifoSize_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, intgo _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->fifoSize = arg2;
  
}


intgo _wrap_lms_stream_status_t_fifoSize_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->fifoSize);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_status_t_underrun_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, intgo _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->underrun = arg2;
  
}


intgo _wrap_lms_stream_status_t_underrun_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->underrun);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_status_t_overrun_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, intgo _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->overrun = arg2;
  
}


intgo _wrap_lms_stream_status_t_overrun_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->overrun);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_status_t_droppedPackets_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, intgo _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->droppedPackets = arg2;
  
}


intgo _wrap_lms_stream_status_t_droppedPackets_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->droppedPackets);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_status_t_sampleRate_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, double _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  float_type arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (float_type)_swig_go_1; 
  
  if (arg1) (arg1)->sampleRate = arg2;
  
}


double _wrap_lms_stream_status_t_sampleRate_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  float_type result;
  double _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (float_type) ((arg1)->sampleRate);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_status_t_linkRate_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, double _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  float_type arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (float_type)_swig_go_1; 
  
  if (arg1) (arg1)->linkRate = arg2;
  
}


double _wrap_lms_stream_status_t_linkRate_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  float_type result;
  double _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (float_type) ((arg1)->linkRate);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_stream_status_t_timestamp_set_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0, long long _swig_go_1) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint64_t arg2 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  arg2 = (uint64_t)_swig_go_1; 
  
  if (arg1) (arg1)->timestamp = arg2;
  
}


long long _wrap_lms_stream_status_t_timestamp_get_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  uint64_t result;
  long long _swig_go_result;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  result = (uint64_t) ((arg1)->timestamp);
  _swig_go_result = result; 
  return _swig_go_result;
}


lms_stream_status_t *_wrap_new_lms_stream_status_t_limewrap_a37b50197546cf98() {
  lms_stream_status_t *result = 0 ;
  lms_stream_status_t *_swig_go_result;
  
  
  result = (lms_stream_status_t *)calloc(1, sizeof(lms_stream_status_t));
  *(lms_stream_status_t **)&_swig_go_result = (lms_stream_status_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_lms_stream_status_t_limewrap_a37b50197546cf98(lms_stream_status_t *_swig_go_0) {
  lms_stream_status_t *arg1 = (lms_stream_status_t *) 0 ;
  
  arg1 = *(lms_stream_status_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


intgo _wrap_LMS_SetupStream_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, lms_stream_t *_swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  lms_stream_t *arg2 = (lms_stream_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(lms_stream_t **)&_swig_go_1; 
  
  result = (int)LMS_SetupStream(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_DestroyStream_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, lms_stream_t *_swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  lms_stream_t *arg2 = (lms_stream_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(lms_stream_t **)&_swig_go_1; 
  
  result = (int)LMS_DestroyStream(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_StartStream_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  result = (int)LMS_StartStream(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_StopStream_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  
  result = (int)LMS_StopStream(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_RecvStream_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, void *_swig_go_1, long long _swig_go_2, lms_stream_meta_t *_swig_go_3, intgo _swig_go_4) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  lms_stream_meta_t *arg4 = (lms_stream_meta_t *) 0 ;
  unsigned int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(lms_stream_meta_t **)&_swig_go_3; 
  arg5 = (unsigned int)_swig_go_4; 
  
  result = (int)LMS_RecvStream(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetStreamStatus_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, lms_stream_status_t *_swig_go_1) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  lms_stream_status_t *arg2 = (lms_stream_status_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = *(lms_stream_status_t **)&_swig_go_1; 
  
  result = (int)LMS_GetStreamStatus(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_SendStream_limewrap_a37b50197546cf98(lms_stream_t *_swig_go_0, void *_swig_go_1, long long _swig_go_2, lms_stream_meta_t *_swig_go_3, intgo _swig_go_4) {
  lms_stream_t *arg1 = (lms_stream_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  lms_stream_meta_t *arg4 = (lms_stream_meta_t *) 0 ;
  unsigned int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_stream_t **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  arg4 = *(lms_stream_meta_t **)&_swig_go_3; 
  arg5 = (unsigned int)_swig_go_4; 
  
  result = (int)LMS_SendStream(arg1,(void const *)arg2,arg3,(lms_stream_meta_t const *)arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_UploadWFM_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, void **_swig_go_1, char _swig_go_2, long long _swig_go_3, intgo _swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  void **arg2 = (void **) 0 ;
  uint8_t arg3 ;
  size_t arg4 ;
  int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(void ***)&_swig_go_1; 
  arg3 = (uint8_t)_swig_go_2; 
  arg4 = (size_t)_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  
  result = (int)LMS_UploadWFM(arg1,(void const **)arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_EnableTxWFM_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, intgo _swig_go_1, bool _swig_go_2) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  unsigned int arg2 ;
  bool arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  arg3 = (bool)_swig_go_2; 
  
  result = (int)LMS_EnableTxWFM(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_GetProgramModes_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, _gostring_* _swig_go_1) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  lms_name_t *arg2 = (lms_name_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  arg2 = *(lms_name_t **)&_swig_go_1; 
  
  result = (int)LMS_GetProgramModes(arg1,(char (*)[16])arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_LMS_Program_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0, _gostring_ _swig_go_1, long long _swig_go_2, _gostring_ _swig_go_3, void** _swig_go_4) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  char *arg4 ;
  lms_prog_callback_t arg5 = (lms_prog_callback_t) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (size_t)_swig_go_2; 
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  arg5 = *(lms_prog_callback_t *)&_swig_go_4; 
  
  result = (int)LMS_Program(arg1,(char const *)arg2,arg3,(char const (*))arg4,arg5);
  _swig_go_result = result; 
  free(arg2); 
  free(arg4); 
  return _swig_go_result;
}


void _wrap_lms_dev_info_t_deviceName_set_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *arg2 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->deviceName, (const char *)arg2, 32-1);
      arg1->deviceName[32-1] = 0;
    } else {
      arg1->deviceName[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_lms_dev_info_t_deviceName_get_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  result = (char *)(char *) ((arg1)->deviceName);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_lms_dev_info_t_expansionName_set_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *arg2 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->expansionName, (const char *)arg2, 32-1);
      arg1->expansionName[32-1] = 0;
    } else {
      arg1->expansionName[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_lms_dev_info_t_expansionName_get_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  result = (char *)(char *) ((arg1)->expansionName);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_lms_dev_info_t_firmwareVersion_set_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *arg2 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->firmwareVersion, (const char *)arg2, 16-1);
      arg1->firmwareVersion[16-1] = 0;
    } else {
      arg1->firmwareVersion[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_lms_dev_info_t_firmwareVersion_get_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  result = (char *)(char *) ((arg1)->firmwareVersion);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_lms_dev_info_t_hardwareVersion_set_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *arg2 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->hardwareVersion, (const char *)arg2, 16-1);
      arg1->hardwareVersion[16-1] = 0;
    } else {
      arg1->hardwareVersion[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_lms_dev_info_t_hardwareVersion_get_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  result = (char *)(char *) ((arg1)->hardwareVersion);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_lms_dev_info_t_protocolVersion_set_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *arg2 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->protocolVersion, (const char *)arg2, 16-1);
      arg1->protocolVersion[16-1] = 0;
    } else {
      arg1->protocolVersion[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_lms_dev_info_t_protocolVersion_get_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  result = (char *)(char *) ((arg1)->protocolVersion);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_lms_dev_info_t_boardSerialNumber_set_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0, long long _swig_go_1) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  uint64_t arg2 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  arg2 = (uint64_t)_swig_go_1; 
  
  if (arg1) (arg1)->boardSerialNumber = arg2;
  
}


long long _wrap_lms_dev_info_t_boardSerialNumber_get_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  uint64_t result;
  long long _swig_go_result;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  result = (uint64_t) ((arg1)->boardSerialNumber);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lms_dev_info_t_gatewareVersion_set_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *arg2 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->gatewareVersion, (const char *)arg2, 16-1);
      arg1->gatewareVersion[16-1] = 0;
    } else {
      arg1->gatewareVersion[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_lms_dev_info_t_gatewareVersion_get_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  result = (char *)(char *) ((arg1)->gatewareVersion);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_lms_dev_info_t_gatewareTargetBoard_set_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0, _gostring_ _swig_go_1) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *arg2 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  {
    if(arg2) {
      strncpy((char*)arg1->gatewareTargetBoard, (const char *)arg2, 32-1);
      arg1->gatewareTargetBoard[32-1] = 0;
    } else {
      arg1->gatewareTargetBoard[0] = 0;
    }
  }
  
  free(arg2); 
}


_gostring_ _wrap_lms_dev_info_t_gatewareTargetBoard_get_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  result = (char *)(char *) ((arg1)->gatewareTargetBoard);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


lms_dev_info_t *_wrap_new_lms_dev_info_t_limewrap_a37b50197546cf98() {
  lms_dev_info_t *result = 0 ;
  lms_dev_info_t *_swig_go_result;
  
  
  result = (lms_dev_info_t *)calloc(1, sizeof(lms_dev_info_t));
  *(lms_dev_info_t **)&_swig_go_result = (lms_dev_info_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_lms_dev_info_t_limewrap_a37b50197546cf98(lms_dev_info_t *_swig_go_0) {
  lms_dev_info_t *arg1 = (lms_dev_info_t *) 0 ;
  
  arg1 = *(lms_dev_info_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


lms_dev_info_t *_wrap_LMS_GetDeviceInfo_limewrap_a37b50197546cf98(lms_device_t *_swig_go_0) {
  lms_device_t *arg1 = (lms_device_t *) 0 ;
  lms_dev_info_t *result = 0 ;
  lms_dev_info_t *_swig_go_result;
  
  arg1 = *(lms_device_t **)&_swig_go_0; 
  
  result = (lms_dev_info_t *)LMS_GetDeviceInfo(arg1);
  *(lms_dev_info_t **)&_swig_go_result = (lms_dev_info_t *)result; 
  return _swig_go_result;
}


_gostring_ _wrap_LMS_GetLibraryVersion_limewrap_a37b50197546cf98() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)LMS_GetLibraryVersion();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_LMS_GetLastErrorMessage_limewrap_a37b50197546cf98() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)LMS_GetLastErrorMessage();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_LMS_RegisterLogHandler_limewrap_a37b50197546cf98(void** _swig_go_0) {
  LMS_LogHandler arg1 = (LMS_LogHandler) 0 ;
  
  arg1 = *(LMS_LogHandler *)&_swig_go_0; 
  
  LMS_RegisterLogHandler(arg1);
  
}


#ifdef __cplusplus
}
#endif

